#sinatra:
#  image: sinatra
#  command: bundle exec ruby app.rb
#  ports:
#    - 8080:4567
#  volumes:
#    - ./sinatra:/app
#  links:
#    - redis
#    - postgres
#  environment:
#    - REDIS_HOST=redis
#    - REDIS_PORT=6379
nginx:
  image: nginx
  ports:
    - 8080:80
  links:
    - laravel
laravel:
  image: laravel
#  links:
#    - redis
#    - postgres
#postgres:
#  image: postgres
#redis:
#  image: redis
#es:
#  image: elasticsearch
#  hostname: elasticsearch
#  ports:
#    - "9200:9200"
#    - "9300:9300"
#kibana:
#  image: kibana
#  ports:
#    - "5601:5601"
#  links:
#    - es:es